### PR TITLE
Fixes #17

### LINKED ISSUE #17: [photorec] Feature: Only create report.xml
When recovering from a large disk, one might want to omit some files which are too big, or known to exist elsewhere, etc. Conversely, one might want to compare recoveries with different parameters, different tools, etc.

Currently, one still needs to have enough free disk space to have all these redundant files, or to have all versions of recovery. I suggest to have an option where photorec performs all the analysis, but doesn't actually write the recovered data to disk. It is simple enough, afterwards, to recover the actual files one wants by reading the xml, and most likely much less time consumptive than the original analysis. (Of course, there can also be a feature for processing a report.xml and recovering by its spec, so one can simply delete the items which are unwanted, but I assume this is a much larger feature.)

### PR DESCRIPTION
**Pull request by amosonn**
Fixes #17: Still scatters thumbnails, but other than that it works.

### CODE REVIEW

**Comment by cgsecurity** [comment]
In file_finish_aux(), it will be best to avoid calling set_date(), file_rename() and creating directories for files that are deleted.
In jpg_check_structure() from src/file_jpg.c, avoid to create a jpg thumb file.

**Comment by timofonic** [comment]
@amosonn @cgsecurity Any news about this? Will there be a possible merge?

**Comment by amosonn** [comment]
I haven't had much time to look at it, will try this week.

The first few seem possible. The reason I didn't implement the latter, is that the settings struct is not passed to that context, which makes it hard to determine whether a thumb needs or does not need to be created. I thought about adding it as a field to another struct passed there, but it seemed too ugly to me. If you say that's fine, I can go ahead and do it; otherwise, this requires some more refactoring (passing the settings struct to *all* file formats, which is some).

**Comment by timofonic** [comment]
@cgsecurity Any news?

**Pull request closed without merging**
